CREATE TABLE IF NOT EXISTS `ms_ref` (
  `id` INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `reference_code` varchar(15) NOT NULL ,
  `timestamp` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;